version: '3'

services:
 validator0:
   container_name: validator0
   image: cosmoscontracts/juno:latest
   ports:
   - "26656-26657:26656-26657"
   - "1317:1317"
   volumes:
   - ./workspace:/workspace
   command: /bin/sh -c 'junod start --home /workspace/test-chain-id/validator0'
   networks:
     localnet:
       ipv4_address: 192.168.10.0

 validator1:
   container_name: validator1
   image: cosmoscontracts/juno:latest
   ports:
   - "26658-26659:26656-26657"
   - "1318:1317"
   volumes:
   - ./workspace:/workspace
   command: /bin/sh -c 'junod start --home /workspace/test-chain-id/validator1'
   networks:
     localnet:
       ipv4_address: 192.168.10.1

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
